version: "3.9"

services:
  yolo-server:
    build: .
    container_name: yolo-fastapi
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
