services:
  yolo-fastapi:
    build:
      dockerfile: Dockerfile
    image: yolo-fastapi
    command: ["python", "main.py"]
    restart: on-failure:5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: "host"

networks:
  mynetwork:
    driver: bridge
